name: Run tests on Java

on:  # yamllint disable-line rule:truthy
  pull_request:
    - types: [opened, reopened]

jobs:
  test:
    strategy:
      matrix:
        version: [8, 11, 21]
    runs-on: ubuntu-latest
    name: Run unit tests on Java ${{ matrix.version }}
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}
      - run: mvn -f pom.xml test
